name: Auto-Merge Release Please PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'github-actions[bot]' && contains(github.event.pull_request.title, 'release-please')
    steps:
      - name: Enable auto-merge
        run: |
          gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}
        env:
          GITHUB_TOKEN: ${{ github.token }}