name: Reusable Python CI

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main
      - 'feature/*'
  workflow_dispatch:  # Allows manual trigger

jobs:
  python-ci:
    uses: Alkimi-Exchange/composite-actions/.github/workflows/python-ci.yml@main
    with:
      python-version: "3.10"
      sonar-project-key: "my-python-project"
      sonar-organization: "Alkimi-Exchange"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Added for failure notifications
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
