name: Build and Push Docker Image
description: |
  Builds and pushes a Docker image to GitHub Container Registry.
  Supports multi-platform builds and custom build arguments.

on:
  workflow_call:
    inputs:
      buildArgs:
        description: 'Build arguments'
        required: false
        type: string
      platforms:
        description: 'Target platforms (comma-separated)'
        required: false
        default: 'linux/amd64'
        type: string
      tags:
        description: 'Image tags (comma-separated)'
        required: false
        type: string
      push:
        description: 'Push Docker Image'
        required: false
        default: true
        type: boolean
      context:
        description: 'Docker context'
        required: false
        default: '.'
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Convert Repository Name to Lowercase
        run: |
            echo "IMAGE_TAG=$(echo ${{ inputs.tags }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          push: ${{ inputs.push }}
          tags: ${{ env.IMAGE_TAG }}
          platforms: ${{ inputs.platforms }}
          build-args: ${{ inputs.buildArgs }}
          secrets: |
            GITHUB_TOKEN=${{ github.token }}
