name: Notify Slack

on:
  workflow_call:
    inputs:
      SLACK_MESSAGE:
        description: "Message to send to Slack"
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  send_slack_notification:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: ${{ inputs.SLACK_MESSAGE }}
