name: Python CI

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        required: false
        default: "3.10"
        type: string
      gcp-project-id: 
        description: "GCP Project Id"
        required: false
        default: "semiotic-primer-427106-p1"
        type: string
    secrets:
      SONAR_HOST_URL:
        required: true
      SONAR_TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: false
      SNYK_TOKEN:
        required: false
      GCR_JSON_KEY:
        required: true

jobs:
  docker_build:
    uses: Alkimi-Exchange/composite-actions/.github/workflows/docker-build.yml@main
    with:
      push: true
      gcp-project-id: ${{ inputs.gcp-project-id }}
    secrets:
      GCR_JSON_KEY: ${{ secrets.GCR_JSON_KEY }}

  build_lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pylint pytest

      - name: Run Flake8 Linter
        continue-on-error: true
        run: flake8 . --count --show-source --statistics
          
      - name: Run Pylint (Fail if Score < 5)
        continue-on-error: true
        run: pylint $(git ls-files '*.py') --fail-under=5

      - name: Run Tests with Pytest
        continue-on-error: true
        run: pytest --junitxml=test-results.xml

      - name: Upload Test Results
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml

  security_scan_snyk:
    needs: build_lint_test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Snyk Security Scan
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --skip-unresolved=true

  code_quality_sonar:
    needs: build_lint_test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  release-please:
    needs: [docker_build, code_quality_sonar, security_scan_snyk]
    if: success()
    uses: Alkimi-Exchange/composite-actions/.github/workflows/release.yml@main
    with:
      release-type: "python"
      gcp-project-id: ${{ inputs.gcp-project-id }}
    secrets:
      GCR_JSON_KEY: ${{ secrets.GCR_JSON_KEY }}
  

  notify_ci_failure:
    needs: [build_lint_test, security_scan_snyk, code_quality_sonar, release-please]
    if: failure()
    uses: Alkimi-Exchange/composite-actions/.github/workflows/notify.yml@main
    with:
      SLACK_MESSAGE: "🚨 Build failed in *${{ github.repository }}* on `${{ github.ref_name }}`"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
