name: Scan Docker Image
description: |
  Scan Docker Image

on:
  workflow_call:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Get Image Tag
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "IMAGE_TAG=ghcr.io/${REPO_LOWER}:${SHORT_SHA}" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
